export interface Route {
  name: string;
  cities: string[];
}

export const ROUTES: Route[] = [
  {
    name: "ABAIRA - ROTA 03.4",
    cities: [
      "ABAIRA",
      "ABAÍRA",
      "Abaira",
      "Abaíra",
      "Catolés",
      "Catolés Abaíra",
    ],
  },
  {
    name: "ANAGE - RETIRA 05",
    cities: [
      "ANAGE",
      "ANAGE (BA)",
      "ANAGÉ",
      "Anage",
      "Anagé",
    ],
  },
  {
    name: "ARACATU - ROTA 05",
    cities: [
      "ARACATU",
      "ARACATU (BA)",
      "Aracatu",
    ],
  },
  {
    name: "BARRA DO CHOÇA - RETIRA 06",
    cities: [
      "BARRA DO CHO?A",
      "BARRA DO CHOÇA",
      "BARRA DO CHOCA",
      "BARRA DO CHOCA (BA)",
      "BARRA NOVA",
      "Barra Do Choça",
      "Barra do Choça",
      "Barra Do Choca",
      "Barra do Choca",
      "Barra Nova",
      "Barra Nova (Barra do Choça)",
    ],
  },
  {
    name: "BELO CAMPO - RETIRA 03",
    cities: [
      "BELO CAMPO",
      "BELO CAMPO (BA)",
      "Belo Campo",
    ],
  },
  {
    name: "BOA NOVA - ROTA 01",
    cities: [
      "BOA NOVA",
      "BOA NOVA (BA)",
      "Boa Nova",
    ],
  },
  {
    name: "BOM JESUS DA SERRA - ROTA 01",
    cities: [
      "BOM JESUS DA SERRA",
      "Bom Jesus Da Serra",
    ],
  },
  {
    name: "BRUMADO - ROTA 05.1",
    cities: [
      "BRUMADO",
      "BRUMADO (BA)",
      "Brumado",
      "Itaquaraí",
      "Samambaia",
      "Ubiracaba",
      "Ubiracaba (Brumado)",
    ],
  },
  {
    name: "CACULE - ROTA 05.2",
    cities: [
      "CACULE (BA)",
      "CACULÉ",
      "Cacule",
      "Caculé",
    ],
  },
  {
    name: "CAETANOS - RETIRA 01",
    cities: [
      "CAETANOS",
      "Caetanos",
    ],
  },
  {
    name: "CAETITE - ROTA 05.3",
    cities: [
      "Brejinho Das Ametistas",
      "Brejinho das Ametistas",
      "CAETITE (BA)",
      "CAETITÉ",
      "Caetite",
      "Caetité",
      "Maniaçu",
      "Pajeu Do Vento",
      "Pajeu do Vento",
    ],
  },
  {
    name: "CANDIBA - ROTA 05.4",
    cities: [
      "CANDIBA",
      "CANDIBA (BA)",
      "Candiba",
      "Pilões",
    ],
  },
  {
    name: "CANDIDO SALES - RETIRA 02",
    cities: [
      "CANDIDO SALES (BA)",
      "CÂNDIDO SALES",
      "Candido Sales",
      "Cândido Sales",
      "LAGOA GRANDE",
      "Lagoa Grande",
      "QUARAÇU",
      "Quaraçu",
    ],
  },
  {
    name: "CARAIBAS - RETIRA 05",
    cities: [
      "CARAÍBAS",
      "Caraibas",
      "Caraíbas",
      "Jânio Quadros",
      "Jânio quadros",
      "PRESIDENTE JÂNIO QUADROS",
      "Presidente Jânio Quadros",
    ],
  },
  {
    name: "CARIRANHA - ROTA 05.4",
    cities: [
      "Agrovila XV",
      "CARINHANHA",
      "CARINHANHA (BA)",
      "Carinhanha",
    ],
  },
  {
    name: "CONDEUBA - RETIRA 03",
    cities: [
      "Alegre",
      "CONDEUBA (BA)",
      "CONDEÚBA",
      "Condeuba",
      "Condeúba",
    ],
  },
  {
    name: "CORDEIROS - RETIRA 03",
    cities: [
      "CORDEIROS",
      "CORDEIROS (BA)",
      "Cordeiros",
    ],
  },
  {
    name: "DOM BASILIO - ROTA 03.3",
    cities: [
      "DOM BASILIO",
      "DOM BASILIO (BA)",
      "DOM BASÍLIO",
      "DOM BASÍLIO (BA)",
      "Dom Basilio",
      "Dom Basílio",
    ],
  },
  {
    name: "ERICO CARDOSO - ROTA 03.2",
    cities: [
      "ERICO CARDOSO (BA)",
      "ÉRICO CARDOSO",
      "Erico Cardoso",
      "Érico Cardoso",
    ],
  },
  {
    name: "GUAJERU - ROTA 05.2",
    cities: [
      "GUAJERU",
      "Guajeru",
    ],
  },
  {
    name: "GUANAMBI - ROTA 05.5",
    cities: [
      "GUANAMBI",
      "GUANAMBI (BA)",
      "GUANAMBI (Ba)",
      "Guanambi",
      "Guanambi (BA)",
      "Guanambi (Ba)",
      "Guanambi (ba)",
      "Morrinhos",
      "Mutas",
      "Mutas (Guanambi)",
      "Tanque Novo",
      "Tanque novo",
    ],
  },
  {
    name: "IBICUI - ROTA 01",
    cities: [
      "IBICUÍ",
      "Ibicui",
      "Ibicuí",
    ],
  },
  {
    name: "IBISSUCE - ROTA 05.2",
    cities: [
      "IBIASSUCE (BA)",
      "IBIASSUCÊ",
      "Ibiassuce",
      "Ibiassucê",
    ],
  },
  {
    name: "IGUAI - ROTA 02",
    cities: [
      "IGUA?",
      "IGUAI (BA)",
      "IGUAÍ",
      "Iguai",
      "Iguaí",
      "Iguaibi",
    ],
  },
  {
    name: "ITAMBÉ - ROTA 04",
    cities: [
      "ITAMBE",
      "ITAMBÉ",
      "Itambe",
      "Itambé",
    ],
  },
  {
    name: "ITAPETINGA - ROTA 04",
    cities: [
      "Bandeira Do Colônia (Itapetinga)",
      "Bandeira do Colônia (Itapetinga)",
      "ITAPETINGA",
      "ITAPETINGA (BA)",
      "ITAPITANGA",
      "Itapetinga",
      "Itapitanga",
    ],
  },
  {
    name: "ITARANTIM - ROTA 04",
    cities: [
      "ITARANTIM",
      "Itarantim",
    ],
  },
  {
    name: "ITORORO - ROTA 04",
    cities: [
      "BANDEIRA DO COLONIA",
      "Bandeira Do Colonia",
      "ITATI",
      "Itati",
      "ITORORO (BA)",
      "ITORORÓ",
      "Itororo",
      "Itororó",
      "RIO DO MEIO",
      "Rio Do Meio",
    ],
  },
  {
    name: "ITUAÇU - ROTA 03",
    cities: [
      "ANDARAI",
      "Andarai",
      "BARRA DA ESTIVA",
      "BARRA DA ESTIVA (BA)",
      "Barra Da Estiva",
      "Barra da Estiva",
      "Caraibuna",
      "CONTENDAS DO SINCORA",
      "CONTENDAS DO SINCORA (BA)",
      "CONTENDAS DO SINCORÁ",
      "CONTENDAS DO SINCORÁ (BA)",
      "Contendas Do Sincora",
      "Contendas do Sincora",
      "Contendas Do Sincorá",
      "Contendas do Sincorá",
      "IBICOARA",
      "IBICOARA (BA)",
      "Ibicoara",
      "ITAETE",
      "ITAETÉ",
      "Itaete",
      "Itaeté",
      "ITUACU",
      "ITUACU (BA)",
      "ITUAÇU",
      "Ituacu",
      "Ituaçu",
      "TANHACU",
      "TANHACU (BA)",
      "TANHAÇU",
      "Tanhacu",
      "Tanhaçu",
      "Triunfo Do Sincorá",
      "Triunfo do Sincorá",
    ],
  },
  {
    name: "IUIU - ROTA 05.4",
    cities: [
      "IUIÚ",
      "Iuiu",
      "Iuiú",
      "PINDORAMA/IUIU",
      "Pindorama (Iuiu)",
    ],
  },
  {
    name: "JACARACI - ROTA 05.4",
    cities: [
      "IRUNDIARA (JACARACI)",
      "Irundiara",
      "Irundiara (Jacaraci)",
      "JACARACI",
      "Jacaraci",
    ],
  },
  {
    name: "JUSSIAPE - ROTA 03.4",
    cities: [
      "Caraguataí",
      "JUSSIAPE",
      "JUSSIAPE CARAGUATAI",
      "Jussiape",
      "Jussiape Caraguatai",
    ],
  },
  {
    name: "LAGOA REAL - ROTA 05.2",
    cities: [
      "LAGOA REAL",
      "Lagoa Real",
    ],
  },
  {
    name: "LICINIO DE ALMEIDA - ROTA 05.4",
    cities: [
      "LICÍNIO DE ALMEIDA",
      "Licinio De Almeida",
      "Licínio De Almeida",
      "Tauapé",
    ],
  },
  {
    name: "LIVRAMENTO - ROTA 03.3",
    cities: [
      "Itanagé",
      "LIVRAMENTO DE N SENHORA",
      "LIVRAMENTO DE NOSSA SENHORA",
      "LIVRAMENTO DE NOSSA SENHORA (BA)",
      "Livramento",
      "Livramento De N Senhora",
      "Livramento De Nossa Senhora",
      "livramento",
    ],
  },
  {
    name: "MACARANI - ROTA 04",
    cities: [
      "MACARANI",
      "MACARANI (BA)",
      "Macarani",
    ],
  },
  {
    name: "MAETINGA - RETIRA 05",
    cities: [
      "MAETINGA",
      "MAETINGA (BA)",
      "Maetinga",
    ],
  },
  {
    name: "MAIQUENIQUE - ROTA 04",
    cities: [
      "MAIQUINIQUE",
      "MAIQUINIWUE",
      "Maiquinique",
      "Maiquiniwue",
    ],
  },
  {
    name: "MALHADA DE PEDRAS - ROTA 05.2",
    cities: [
      "MALHADA DE PEDRAS",
      "Malhada De Pedras",
      "Malhada de Pedras",
    ],
  },
  {
    name: "MALHADA - ROTA 05.4",
    cities: [
      "Cana Brava",
      "MALHADA",
      "MALHADA (BA)",
      "Malhada",
      "Parateca",
    ],
  },
  {
    name: "MATINA - ROTA 05.4",
    cities: [
      "MATINA",
      "Matina",
    ],
  },
  {
    name: "MIRANTE - ROTA 01",
    cities: [
      "MIRANTE",
      "Mirante",
    ],
  },
  {
    name: "MORTUGABA - ROTA 05.4",
    cities: [
      "MORTUGABA",
      "Mortugaba",
      "Mortu6",
    ],
  },
  {
    name: "NOVA CANAÃ - ROTA 02",
    cities: [
      "ITAJAÍ",
      "NOVA CANAÃ",
      "Itajaí",
      "Nova Canaã",
    ],
  },
  {
    name: "PALMAS DE MONTE ALTO - ROTA 05.4",
    cities: [
      "PALMAS DE MONTE ALTO",
      "PALMAS DE MONTE ALTO (BA)",
      "Palmas De Monte Alto",
      "Palmas de Monte Alto",
      "Rancho Das Mães",
      "Rancho das Mães",
    ],
  },
  {
    name: "PARAMIRIM - ROTA 03.2",
    cities: [
      "Canabravinha",
      "PARAMIRIM",
      "PARAMIRIM (BA)",
      "Paramirim",
    ],
  },
  {
    name: "PIATÃ - ROTA 03.5",
    cities: [
      "Cabralia",
      "Cabrália",
      "Cabrália (Piatã)",
      "Inúbia",
      "Inúbia (Piatã)",
      "PIATA (BA)",
      "Piata",
      "Piatã",
    ],
  },
  {
    name: "PINDAI - ROTA 05.4",
    cities: [
      "Guirapa",
      "PINDAÍ",
      "Pindai",
      "Pindaí",
    ],
  },
  {
    name: "PIRIPA - RETIRA 03",
    cities: [
      "PIRIPA (BA)",
      "PIRIPÁ",
      "Piripa",
      "Piripá",
    ],
  },
  {
    name: "PLANALTO - ROTA 01",
    cities: [
      "LUCAIA",
      "PLANALTO",
      "PLANALTO (BA)",
      "Lucaia",
      "Planalto",
    ],
  },
  {
    name: "POÇÕES - ROTA 01",
    cities: [
      "PO??ES",
      "POCOES",
      "POCOES (BA)",
      "POÇÕES",
      "Pocoes",
      "Poções",
    ],
  },
  {
    name: "POTIRAGUA - ROTA 04",
    cities: [
      "POTIRAGUA",
      "Potiragua",
    ],
  },
  {
    name: "RIO DE CONTAS - ROTA 03.3",
    cities: [
      "Arapiranga",
      "MARCOLINO MOURA",
      "Marcolino Moura",
      "Mato Grosso",
      "RIO DE CONTAS",
      "Rio De Contas",
      "Rio de Contas",
    ],
  },
  {
    name: "RIO DO ANTONIO - ROTA 05.2",
    cities: [
      "IBITIRA",
      "Ibitira",
      "Ibitira (Rio do Antônio)",
      "Ibitira - Rio Antônio",
      "Ibitira - Rio do Antônio",
      "RIO DO ANT?NIO",
      "RIO DO ANTÔNIO",
      "RIO DO ANTONIO",
      "RIO DO ANTONIO (BA)",
      "Rio Do Antônio",
      "Rio do Antônio",
    ],
  },
  {
    name: "SEBASTIÃO LARANJEIRAS - ROTA 05.4",
    cities: [
      "Boquira",
      "Mandiroba",
      "SEBASTIAO LARANJEIRAS",
      "SEBASTIÃO LARANJEIRAS",
      "Sebastiao Laranjeiras",
      "Sebastião Laranjeiras",
    ],
  },
  {
    name: "TREMENDAL - RETIRA 03",
    cities: [
      "Lagoa Preta",
      "TREMEDAL",
      "TREMEDAL (BA)",
      "Tremedal",
    ],
  },
  {
    name: "URANDI - ROTA 05.4",
    cities: [
      "URANDI",
      "Urandi",
    ],
  },
  {
    name: "VCA",
    cities: [
      "Angra Dos Reis",
      "Angra dos Reis",
      "Arcoverde",
      "Bate Pé",
      "Belford Roxo",
      "Belo Horizonte",
      "Cariacica",
      "Esmeraldas",
      "Eusébio",
      "Inhobim",
      "JUIZ DE FORA",
      "Joinville",
      "José Gonçalves",
      "José Gonçalves (Vitória da Conqu",
      "Juiz De Fora",
      "Juiz de Fora",
      "Jundiaí",
      "Lagoa José Luís",
      "Manhuaçu",
      "Maricá",
      "Mauá",
      "Muzambinho",
      "Nova Mutum",
      "Paço Do Lumiar",
      "Paço do Lumiar",
      "Porto Alegre",
      "Pradoso",
      "Sertãozinho",
      "São João Da Vitória",
      "São João da Vitória",
      "São Manuel",
      "São Sebastião",
      "V.CONQUISTA",
      "VIT?RIA DA CONQUISTA",
      "VITARIA DA CONQUISTA",
      "VITORIA DA CONQUISTA",
      "VITORIA DA CONQUISTA (BA)",
      "VITORIA DA CONQUISTA/BA",
      "VITÓRIA DA CONQUISTA",
      "VITÓRIA DACONQUISTA",
      "Vitaria Da Conquista",
      "Vitoria Da Conquista",
      "Vitória Da Conquista",
      "Vitória Daconquista",
      "Vitória da Conquista",
      "Vitria da Conquista",
    ],
  },
];

/** Retorna a rota correspondente a uma cidade (comparação case-insensitive) */
export function findRouteForCity(city: string): Route | undefined {
  const lower = city.toLowerCase();
  return ROUTES.find((r) =>
    r.cities.some((c) => c.toLowerCase() === lower),
  );
}
